### ISSUE TITLE
Package %NK not found on Mac OS X

### ISSUE THREAD

**Issue by chuchana** [borodust/bodge-nuklear#2]
bodge-nuklear does not load on my computer with the latest Mac OS, SBCL, CCL, Quicklisp & org.borodust.bodge dist, and with Mac OS X 10.11 on another computer. It loads without any problems on Arch Linux.

The displayed error is `Package %NK does not exist.` on SBCL and `Error: There is no package named "%NK"` on CCL64.

**Comment by borodust** [comment]
I'm going to try reproducing this error soon. But in the meantime, can you please cleanup common-lisp caches (`rm -rf ~/.cache/common-lisp/*`), remove everything from (~/quicklisp/local-projects/), restart implementation (if it is running), do
```lisp
(ql-dist:install-dist "http://bodge.borodust.org/dist/org.borodust.bodge.txt" :prompt nil :replace t)
(ql:update-all-dists)
```
and try again?

**Comment by chuchana** [comment]
Thank you, that fixed it! I assume it had something to do with the caches, since it now also loads with the local-projects folder back in place.
